title: "2025-2학기 전공필기"
description: "체계적으로 정리한 컴퓨터공학 전공 노트"
baseurl: "/25-02"
url: "https://gwonsujin.github.io"

# 테마 설정
theme: minima
markdown: kramdown

# 플러그인
plugins:
  - jekyll-feed
  - jekyll-sitemap

# 네비게이션
header_pages:
  - index.md
  - processed/2-1-cpu-architecture.md

# 컬렉션 설정
collections:
  notes:
    output: true
    permalink: /:collection/:name/

# 한국어 설정
lang: ko-KR
timezone: Asia/Seoul 
